[package]
name = "bundle"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
anyhow = "1.0.93"
clap = { version = "4.5.21", features = ["derive", "env", "string"] }
resolve-path = "0.1.0"
